on:
  push:
    branches:
    - main
    - develop
    - release-*
    - feature/*  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main
    - develop
    - release-*
    - feature/*  
  workflow_dispatch:

name: Build and Test Code

jobs:
  build-artifacts:
    name: Build Java Artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        submodules: recursive
        fetch-depth: 0
    
    # -------------------------
    # Java Environment Setup
    # -------------------------
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.9.3
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'
        cache: 'maven'
    
    # -------------------------
    # Maven Build
    # -------------------------
    - name: Build and Test Code
      run: |
        mvn clean compile test package
    
    - name: Run Tests and Generate Reports
      run: |
        mvn test
        mvn jacoco:report
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/site/jacoco/
    
    - name: Build JAR File
      run: |
        mvn package -DskipTests
    
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: oscal-cli-jar
        path: cli-core/target/*.jar
    
    - name: Display Build Summary
      if: always()
      run: |
        echo "Build Analysis Complete"
        echo "Checking for JAR files..."
        find . -name "*.jar" -type f || echo "No JAR files found"
        echo "Build process completed"